// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcDWYyCvDiIgPbuoQVgEQMreFIN0ErEUQ',
    appId: '1:223804334449:web:44ba49cddfd4487e9096d0',
    messagingSenderId: '223804334449',
    projectId: 'autozone-premium',
    authDomain: 'autozone-premium.firebaseapp.com',
    storageBucket: 'autozone-premium.firebasestorage.app',
    measurementId: 'G-6GJY8RCV60',
    databaseURL:
        'https://autozone-premium-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8btXARuobwzGqNwmT03aNIWq-pf6DI80',
    appId: '1:223804334449:android:cdce3d25286d0e359096d0',
    messagingSenderId: '223804334449',
    projectId: 'autozone-premium',
    storageBucket: 'autozone-premium.firebasestorage.app',
    databaseURL:
        'https://autozone-premium-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}